on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install system libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            pandoc \
            libx11-dev \
            libcurl4-openssl-dev \
            libssl-dev \
            zlib1g-dev \
            libfreetype-dev \
            libjpeg-dev \
            libpng-dev \
            libtiff-dev \
            libwebp-dev \
            libicu-dev \
            libfontconfig1-dev \
            libfribidi-dev \
            libharfbuzz-dev \
            libxml2-dev

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Python and Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - run: pip install jupyter
      - run: pip install -r requirements.txt

      - name: install quarto tinytex
        run: quarto install tinytex
      - name: Cache Quarto extensions
        uses: actions/cache@v4
        with:
          path: ~/.quarto/extensions
          key: ${{ runner.os }}-quarto-extensions
      - name: install fontawesome
        run: quarto add quarto-ext/fontawesome -y

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
